# Generated by Django 3.2.9 on 2021-11-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField(db_column='file_name', null=True)),
                ('content', models.TextField()),
                ('file_path', models.CharField(db_column='file_path', max_length=250, null=True)),
                ('upload_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'paper',
            },
        ),
    ]
