# Generated by Django 3.2.5 on 2021-11-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0002_auto_20211122_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='content',
            field=models.TextField(db_column='content', null=True),
        ),
    ]
