# Generated by Django 3.2.9 on 2021-12-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0003_alter_paper_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='file_text',
            field=models.TextField(db_column='file_text', null=True),
        ),
    ]
