# Generated by Django 3.2.5 on 2021-12-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0004_paper_file_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='file_text',
            field=models.TextField(db_column='file_text', max_length=4080, null=True),
        ),
    ]
