# Generated by Django 3.1.6 on 2021-12-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0006_paper_page_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='file_text',
            field=models.TextField(db_column='file_text', null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
